spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.couchbase.CouchbaseAutoConfiguration
      - org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.couchbase.CouchbaseRepositoriesAutoConfiguration

couchbase:
  enabled: false

kafka:
  host: localhost:9092,localhost:9094
  client-id: notification-svc
  topics:
    user-created:
      topic: user-service.user_created.1
      consumerGroup: notification-service-user-created-consumer
