# KRaft broker 3 (spring-boot-kafka workflow). SASL :9096

process.roles=broker
node.id=4
controller.quorum.voters=1@localhost:9093

listeners=SASL_PLAINTEXT://:9096
advertised.listeners=SASL_PLAINTEXT://localhost:9096
inter.broker.listener.name=SASL_PLAINTEXT
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL

sasl.enabled.mechanisms=SCRAM-SHA-256
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-256

authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
super.users=User:admin;User:ANONYMOUS

log.dirs=/tmp/kafka-logs-sbk-sasl-broker-3
num.partitions=3
default.replication.factor=4
min.insync.replicas=2
offsets.topic.replication.factor=4
transaction.state.log.replication.factor=4
transaction.state.log.min.isr=2
