bootstrap.servers=localhost:9092,localhost:9094,localhost:9096,localhost:9098
client.id=notification-svc
group.id=notification-service-user-created-consumer
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="notification-svc" password="notification-secret";

kafka.host=localhost:9092,localhost:9094,localhost:9096,localhost:9098
kafka.client-id=notification-svc
kafka.topics.user-created.topic=user-service.user_created.1
kafka.topics.user-created.consumerGroup=notification-service-user-created-consumer
