bootstrap.servers=localhost:9092,localhost:9094,localhost:9096,localhost:9098
client.id=user-svc
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user-svc" password="user-secret";

kafka.host=localhost:9092,localhost:9094,localhost:9096,localhost:9098
kafka.client-id=user-svc
kafka.topics.user-created.topicName=user-service.user_created.1

request.timeout.ms=30000
delivery.timeout.ms=120000
max.block.ms=60000
