bootstrap.servers=localhost:9092,localhost:9094,localhost:9096,localhost:9098
client.id=user-address-svc
group.id=address-service-user-created-consumer
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user-address-svc" password="user-address-secret";

kafka.host=localhost:9092,localhost:9094,localhost:9096,localhost:9098
kafka.client-id=user-address-svc
kafka.topics.user-created.topic=user-service.user_created.1
kafka.topics.user-created.consumerGroup=address-service-user-created-consumer
